# ===============================
# 1. SERVER CONFIGURATION
# ===============================
server.port=8080

# ===============================
# 2. DATABASE CONFIGURATION (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/air_quality_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Settings (Automatically creates/updates your SQL tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# 3. EMAIL NOTIFICATION CONFIGURATION
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dhakatebhagyashree85@gmail.com
spring.mail.password=mvfxixgfahfurpgy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# WAQI API Token for Real-Time Air Quality Data
waqi.api.token=980b9f8a35129bda30f4a9d0c7a7b3f618ea9665
